services:
  - type: web
    name: agar3d-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.13.1
      - key: DATABASE_PATH
        value: ./data/agar3d.sqlite

  - type: static
    name: agar3d-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://agar3d-byw8.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
